# Generated by Django 5.1 on 2024-08-30 21:04

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identity_document', models.CharField(blank=True, default=None, max_length=15, null=True)),
                ('is_connected', models.BooleanField(default=True)),
                ('bio', models.TextField(blank=True, default=None, max_length=500, null=True)),
                ('location', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('birth_date', models.DateField(blank=True, default=None, null=True)),
                ('image', models.ImageField(default='images/profile_pics/avatar.png', upload_to='uploads/profile_pics/')),
                ('date_joined', models.DateField(blank=True, default=None, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
