# Generated by Django 5.1 on 2024-08-30 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_workshift'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='work_shift',
            field=models.ForeignKey(blank=True, help_text='Assigned work shift', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.workshift'),
        ),
        migrations.AddField(
            model_name='profile',
            name='worker_area',
            field=models.ForeignKey(blank=True, help_text='Assigned worker area', null=True, on_delete=django.db.models.deletion.SET_NULL, to='employee.workerarea'),
        ),
    ]
