# Generated by Django 5.1 on 2024-09-01 13:19

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_profile_work_shift_profile_worker_area'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(blank=True, help_text='Video file of the employee during their shift', null=True, upload_to='uploads/emotion_videos/')),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now, help_text='Date and time when the video was recorded')),
                ('analyzed_at', models.DateTimeField(blank=True, help_text='Date and time when the video was analyzed', null=True)),
                ('emotions_detected', models.JSONField(blank=True, help_text='JSON field to store detected emotions and their probabilities', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('profile', models.ForeignKey(help_text='The profile of the employee being analyzed', on_delete=django.db.models.deletion.CASCADE, to='employee.profile')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
